[package]
name = "viax-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
cynic = { version = "3", features = ["rkyv"] }

[build-dependencies]
cynic-codegen = { version = "3", features = ["rkyv"] }
