"""
A Url scalar
"""
scalar Url

"""
A file part in a multipart request
"""
scalar Upload

"""
A universally unique identifier compliant UUID Scalar
"""
scalar UUID

"""
A slightly refined version of RFC-3339 compliant DateTime Scalar
"""
scalar DateTime

"""
An object scalar
"""
scalar Object

"""
A 64-bit signed integer
"""
scalar Long

"""
A scalar which represents tuple value
"""
scalar Tuple

"""
A URN scalar
"""
scalar Urn

"""
Audit data of a specific GraphQL Object instance.

*@incubating*
"""
type Audit {
    """
    Creation transaction.

    *@incubating*
    """
    createdAt: AuditPoint
    """
    Full transaction history in chronological order.

    *@incubating*
    """
    history: [AuditPoint!]
    """
    `true` if instance does not exist anymore in present time.

    *@incubating*
    """
    removed: Boolean
    """
    Retraction transaction.

    *@incubating*
    """
    retractedAt: AuditPoint
    """
    Last update transaction.

    *@incubating*
    """
    updatedAt: AuditPoint
}

"""
Specific point in time inside transaction history.

*@incubating*
"""
type AuditPoint {
    """
    Date & Time of transaction.

    *@incubating*
    """
    dateTime: DateTime
    """
    All changes to GraphQL Object field values within this transaction.

    *@incubating*
    """
    fieldsHistory: [FieldHistory!]
    """
    PartyAccount ID of the transaction author.

    *@incubating*
    """
    partyAccount: String
    """
    *@incubating*
    """
    timestamp: DateTime @deprecated(reason: "Temporary until ui uses new audit")
    """
    Transaction ID.

    *@incubating*
    """
    transactionId: Long
    """
    *@incubating*
    """
    user: String @deprecated(reason: "Temporary until ui uses new audit")
}

"""
Historical change of a specific GraphQL Object field value.

*@incubating*
"""
type FieldHistory {
    """
    Field name.

    *@incubating*
    """
    name: String
    """
    New field value.

    *@incubating*
    """
    newValue: FieldValue
    """
    Old field value.

    *@incubating*
    """
    oldValue: FieldValue
}

"""
GraphQL Object field value.

*@incubating*
"""
type FieldValue {
    """
    Mapping code.

    *@incubating*
    """
    mappingCode: String
    """
    Field value type name

    *@incubating*
    """
    type: String
    """
    Field value.

    *@incubating*
    """
    value: Object
    """
    *@incubating*
    """
    valueType: String @deprecated(reason: "Temporary until ui uses new audit")
}

"""
Represents specific instance of primary key

*@incubating*
"""
type PK {
    """
    Name of unique field the primary key refers to

    *@incubating*
    """
    fieldName: String!
    """
    *@incubating*
    """
    typeName: String!
    """
    Unique value among the values provided by the paid <typeName> + <fieldName. Returned value is a value serialized to a string from original value provided by <typeName>/<fieldName>

    *@incubating*
    """
    value: ID!
}

"""
*@incubating*
"""
type ModelsOrderingInfo implements Auditable & Model & Node & ValueOrderingInfo {
    """
    *@incubating*
    """
    addingTime: DateTime
    """
    When values are present then modifying/deleting is allowed only by users mentioned in this list. When a model is mutated and empty list is added that it is treated as a setting of 'allowedToModifyFor' for the current user otherwise pass null to 'allowedToModifyFor' to turn off read only mode for all other users

    *@incubating*
    """
    allowedToModifyFor: [UUID!]
    """
    Audit log of changes.

    *@incubating*
    """
    auAudit: Audit
    """
    *@incubating*
    """
    compositeKey: Tuple!
    """
    Timestamp indicating when the instance was created.

    *@incubating*
    """
    createdAt: DateTime
    """
    DigitalIdentity of the user who created the instance.

    *@incubating*
    """
    createdBy: DigitalIdentity
    """
    *@incubating*
    """
    field: String!
    """
    Not globally unique low-level DB identifier.

    *@stable*
    """
    id: ID!
    """
    When allowedToModifyFor has values then the value for this field is true for all users which are not mentioned within values of allowedToModifyFor

    *@incubating*
    """
    isReadOnly: Boolean
    """
    Timestamp indicating when the instance was last updated.

    *@incubating*
    """
    modifiedAt: DateTime
    """
    DigitalIdentity of the user who last updated the instance.

    *@incubating*
    """
    modifiedBy: DigitalIdentity
    """
    *@incubating*
    """
    order: Long!
    """
    Primary key.

    Represents a specific *candidate key* used as a default for relationships
    and lookups.

    *@stable*
    """
    pk(typeName: String): PK!
    """
    Primary keys for all types the instance relates to.

    *@incubating*
    """
    pks: [PK!]
    """
    The field is managed internally, links are set automatically when some other model references this model. The main goal of the field to remove automatically instances on removing target models referenced by instance of ModelsOrderingInfo

    *@incubating*
    """
    referencesFromModelsOrderingInfo: [ModelsOrderingInfo!]
    """
    *@incubating*
    """
    source: Model!
    """
    *@incubating*
    """
    target: Model!
    """
    GraphQL type name.

    *@incubating*
    """
    typeName: String!
    """
    Globally unique identifier.

    *@stable*
    """
    uid: UUID!
}

"""
*@incubating*
"""
type UrnOrderingInfo implements Auditable & Model & Node & ValueOrderingInfo {
    """
    *@incubating*
    """
    addingTime: DateTime
    """
    When values are present then modifying/deleting is allowed only by users mentioned in this list. When a model is mutated and empty list is added that it is treated as a setting of 'allowedToModifyFor' for the current user otherwise pass null to 'allowedToModifyFor' to turn off read only mode for all other users

    *@incubating*
    """
    allowedToModifyFor: [UUID!]
    """
    Audit log of changes.

    *@incubating*
    """
    auAudit: Audit
    """
    *@incubating*
    """
    compositeKey: Tuple!
    """
    Timestamp indicating when the instance was created.

    *@incubating*
    """
    createdAt: DateTime
    """
    DigitalIdentity of the user who created the instance.

    *@incubating*
    """
    createdBy: DigitalIdentity
    """
    *@incubating*
    """
    field: String!
    """
    Not globally unique low-level DB identifier.

    *@stable*
    """
    id: ID!
    """
    When allowedToModifyFor has values then the value for this field is true for all users which are not mentioned within values of allowedToModifyFor

    *@incubating*
    """
    isReadOnly: Boolean
    """
    Timestamp indicating when the instance was last updated.

    *@incubating*
    """
    modifiedAt: DateTime
    """
    DigitalIdentity of the user who last updated the instance.

    *@incubating*
    """
    modifiedBy: DigitalIdentity
    """
    *@incubating*
    """
    order: Long!
    """
    Primary key.

    Represents a specific *candidate key* used as a default for relationships
    and lookups.

    *@stable*
    """
    pk(typeName: String): PK!
    """
    Primary keys for all types the instance relates to.

    *@incubating*
    """
    pks: [PK!]
    """
    The field is managed internally, links are set automatically when some other model references this model. The main goal of the field to remove automatically instances on removing target models referenced by instance of ModelsOrderingInfo

    *@incubating*
    """
    referencesFromModelsOrderingInfo: [ModelsOrderingInfo!]
    """
    *@incubating*
    """
    source: Model!
    """
    *@incubating*
    """
    target: Urn!
    """
    GraphQL type name.

    *@incubating*
    """
    typeName: String!
    """
    Globally unique identifier.

    *@stable*
    """
    uid: UUID!
}

"""
*@incubating*
"""
interface ValueOrderingInfo implements Auditable & Model & Node {
    """
    *@incubating*
    """
    addingTime: DateTime
    """
    When values are present then modifying/deleting is allowed only by users mentioned in this list. When a model is mutated and empty list is added that it is treated as a setting of 'allowedToModifyFor' for the current user otherwise pass null to 'allowedToModifyFor' to turn off read only mode for all other users

    *@incubating*
    """
    allowedToModifyFor: [UUID!]
    """
    Audit log of changes.

    *@incubating*
    """
    auAudit: Audit
    """
    Timestamp indicating when the instance was created.

    *@incubating*
    """
    createdAt: DateTime
    """
    DigitalIdentity of the user who created the instance.

    *@incubating*
    """
    createdBy: DigitalIdentity
    """
    *@incubating*
    """
    field: String!
    """
    Not globally unique low-level DB identifier.

    *@stable*
    """
    id: ID!
    """
    When allowedToModifyFor has values then the value for this field is true for all users which are not mentioned within values of allowedToModifyFor

    *@incubating*
    """
    isReadOnly: Boolean
    """
    Timestamp indicating when the instance was last updated.

    *@incubating*
    """
    modifiedAt: DateTime
    """
    DigitalIdentity of the user who last updated the instance.

    *@incubating*
    """
    modifiedBy: DigitalIdentity
    """
    *@incubating*
    """
    order: Long!
    """
    Primary key.

    Represents a specific *candidate key* used as a default for relationships
    and lookups.

    *@stable*
    """
    pk(typeName: String): PK!
    """
    Primary keys for all types the instance relates to.

    *@incubating*
    """
    pks: [PK!]
    """
    The field is managed internally, links are set automatically when some other model references this model. The main goal of the field to remove automatically instances on removing target models referenced by instance of ModelsOrderingInfo

    *@incubating*
    """
    referencesFromModelsOrderingInfo: [ModelsOrderingInfo!]
    """
    *@incubating*
    """
    source: Model!
    """
    GraphQL type name.

    *@incubating*
    """
    typeName: String!
    """
    Globally unique identifier.

    *@stable*
    """
    uid: UUID!
}

"""
Any object that has an identity.

Objects with identities can be distinctly recognized over time, despite any
changes in their state or properties.

Examples include `Customer`, `Order` (with identity) vs. `Money`, `TimePeriod`
(without identity, treated as value objects).

*@stable*
"""
interface Node {
    """
    Not globally unique identifier.

    *@stable*
    """
    id: ID!
    """
    Globally unique identifier.

    *@stable*
    """
    uid: UUID!
}

"""
Audit log support.

*@incubating*
"""
interface Auditable {
    """
    Audit log of changes.

    *@incubating*
    """
    auAudit: Audit
}

"""
*@incubating*
"""
interface DigitalIdentity implements Auditable & Model & Node {
    """
    When values are present then modifying/deleting is allowed only by users mentioned in this list. When a model is mutated and empty list is added that it is treated as a setting of 'allowedToModifyFor' for the current user otherwise pass null to 'allowedToModifyFor' to turn off read only mode for all other users

    *@incubating*
    """
    allowedToModifyFor: [UUID!]
    """
    Audit log of changes.

    *@incubating*
    """
    auAudit: Audit
    """
    Timestamp indicating when the instance was created.

    *@incubating*
    """
    createdAt: DateTime
    """
    DigitalIdentity of the user who created the instance.

    *@incubating*
    """
    createdBy: DigitalIdentity
    """
    *@incubating*
    """
    diLogin: String!
    """
    Not globally unique low-level DB identifier.

    *@stable*
    """
    id: ID!
    """
    When allowedToModifyFor has values then the value for this field is true for all users which are not mentioned within values of allowedToModifyFor

    *@incubating*
    """
    isReadOnly: Boolean
    """
    Timestamp indicating when the instance was last updated.

    *@incubating*
    """
    modifiedAt: DateTime
    """
    DigitalIdentity of the user who last updated the instance.

    *@incubating*
    """
    modifiedBy: DigitalIdentity
    """
    Primary key.

    Represents a specific *candidate key* used as a default for relationships
    and lookups.

    *@stable*
    """
    pk(typeName: String): PK!
    """
    Primary keys for all types the instance relates to.

    *@incubating*
    """
    pks: [PK!]
    """
    The field is managed internally, links are set automatically when some other model references this model. The main goal of the field to remove automatically instances on removing target models referenced by instance of ModelsOrderingInfo

    *@incubating*
    """
    referencesFromModelsOrderingInfo: [ModelsOrderingInfo!]
    """
    GraphQL type name.

    *@incubating*
    """
    typeName: String!
    """
    Globally unique identifier.

    *@stable*
    """
    uid: UUID!
}

"""
Base interface for any *Entity* defined in GraphQL SDL.

An *Entity* is a high-level conceptual representation of a real-world object
or concept modeled in the viax Data Model.

Every *Entity* in viax must implement this interface.

Examples of *Entities*: `Customer`, `Product`, `SalesOrder`, `OrderItem`.

*@stable*
"""
interface Model implements Node {
    """
    When values are present then modifying/deleting is allowed only by users mentioned in this list. When a model is mutated and empty list is added that it is treated as a setting of 'allowedToModifyFor' for the current user otherwise pass null to 'allowedToModifyFor' to turn off read only mode for all other users

    *@incubating*
    """
    allowedToModifyFor: [UUID!]
    """
    Timestamp indicating when the instance was created.

    *@incubating*
    """
    createdAt: DateTime
    """
    DigitalIdentity of the user who created the instance.

    *@incubating*
    """
    createdBy: DigitalIdentity
    """
    Not globally unique low-level DB identifier.

    *@stable*
    """
    id: ID!
    """
    When allowedToModifyFor has values then the value for this field is true for all users which are not mentioned within values of allowedToModifyFor

    *@incubating*
    """
    isReadOnly: Boolean
    """
    Timestamp indicating when the instance was last updated.

    *@incubating*
    """
    modifiedAt: DateTime
    """
    DigitalIdentity of the user who last updated the instance.

    *@incubating*
    """
    modifiedBy: DigitalIdentity
    """
    Primary key.

    Represents a specific *candidate key* used as a default for relationships
    and lookups.

    *@stable*
    """
    pk(typeName: String): PK!
    """
    Primary keys for all types the instance relates to.

    *@incubating*
    """
    pks: [PK!]
    """
    The field is managed internally, links are set automatically when some other model references this model. The main goal of the field to remove automatically instances on removing target models referenced by instance of ModelsOrderingInfo

    *@incubating*
    """
    referencesFromModelsOrderingInfo: [ModelsOrderingInfo!]
    """
    GraphQL type name.

    *@incubating*
    """
    typeName: String!
    """
    Globally unique identifier.

    *@stable*
    """
    uid: UUID!
}

"""
*@incubating*
"""
type File implements Auditable & Model & Node {
    """
    When values are present then modifying/deleting is allowed only by users mentioned in this list. When a model is mutated and empty list is added that it is treated as a setting of 'allowedToModifyFor' for the current user otherwise pass null to 'allowedToModifyFor' to turn off read only mode for all other users

    *@incubating*
    """
    allowedToModifyFor: [UUID!]
    """
    Audit log of changes.

    *@incubating*
    """
    auAudit: Audit
    """
    *@incubating*
    """
    content: String
    """
    *@incubating*
    """
    contentType: String
    """
    Timestamp indicating when the instance was created.

    *@incubating*
    """
    createdAt: DateTime
    """
    DigitalIdentity of the user who created the instance.

    *@incubating*
    """
    createdBy: DigitalIdentity
    """
    Not globally unique low-level DB identifier.

    *@stable*
    """
    id: ID!
    """
    When allowedToModifyFor has values then the value for this field is true for all users which are not mentioned within values of allowedToModifyFor

    *@incubating*
    """
    isReadOnly: Boolean
    """
    Timestamp indicating when the instance was last updated.

    *@incubating*
    """
    modifiedAt: DateTime
    """
    DigitalIdentity of the user who last updated the instance.

    *@incubating*
    """
    modifiedBy: DigitalIdentity
    """
    *@incubating*
    """
    name: String!
    """
    Primary key.

    Represents a specific *candidate key* used as a default for relationships
    and lookups.

    *@stable*
    """
    pk(typeName: String): PK!
    """
    Primary keys for all types the instance relates to.

    *@incubating*
    """
    pks: [PK!]
    """
    The field is managed internally, links are set automatically when some other model references this model. The main goal of the field to remove automatically instances on removing target models referenced by instance of ModelsOrderingInfo

    *@incubating*
    """
    referencesFromModelsOrderingInfo: [ModelsOrderingInfo!]
    """
    GraphQL type name.

    *@incubating*
    """
    typeName: String!
    """
    Globally unique identifier.

    *@stable*
    """
    uid: UUID!
    """
    *@incubating*
    """
    url: Url!
    """
    *@incubating*
    """
    version: String!
}

enum DeployStatus {
    UNKNOWN
    CANCELLED
    DEPLOYING
    DELETING
    FAILED
    TIME_OUT
    ENQUEUED_DEPLOYING
    ENQUEUED_DELETING
    READY
}

enum FunctionSpecialization {
    FUNCTION
    RESOLVER
    PRICING_ELEMENT
}

enum FunctionOrderByFields {
    _score
    createdAt
    deployStatus
    enqueuedAt
    id
    isReadOnly
    latestCreatedRevision
    latestDeploymentStartedAt
    modifiedAt
    name
    pk
    ready
    readyRevision
    runtime
    specialization
    tag
    uid
    url
    urn
    version
}

"""
Ordering (sorting) direction.

*@stable*
"""
enum OrderByDirection {
    """
    *@stable*
    """
    ASC
    """
    *@stable*
    """
    DESC
}

"""
Used as value type by a field 'pageInfo' of connection specific types.

*@incubating*
"""
type PageInfo {
    """
    The cursor corresponding to the last node in edges.

    *@incubating*
    """
    endCursor: String
    """
    Used to indicate whether more edges exist prior to the set defined by the clients arguments.

    *@incubating*
    """
    hasNextPage: Boolean!
    """
    Used to indicate whether more edges exist following the set defined by the clients arguments.

    *@incubating*
    """
    hasPreviousPage: Boolean!
    """
    The cursor corresponding to the first node in edges.

    *@incubating*
    """
    startCursor: String
}

"""
Pagination support.

@deprecated(reason: "Will be removed in future versions in favor of https://relay.dev/graphql/connections.htm")

*@incubating*
"""
interface Pageable {
    """
    *@incubating*
    """
    currentPage: Int
    """
    *@incubating*
    """
    pageSize: Int
    """
    *@incubating*
    """
    totalCount: Int
    """
    *@incubating*
    """
    totalPages: Int
}

input FunctionOrderByInput {
    direction: OrderByDirection
    field: FunctionOrderByFields!
}

"""
*@incubating*
"""
type IntegrationDeployment implements Auditable & Model & Node {
    """
    When values are present then modifying/deleting is allowed only by users mentioned in this list. When a model is mutated and empty list is added that it is treated as a setting of 'allowedToModifyFor' for the current user otherwise pass null to 'allowedToModifyFor' to turn off read only mode for all other users

    *@incubating*
    """
    allowedToModifyFor: [UUID!]
    """
    Audit log of changes.

    *@incubating*
    """
    auAudit: Audit
    """
    Timestamp indicating when the instance was created.

    *@incubating*
    """
    createdAt: DateTime
    """
    DigitalIdentity of the user who created the instance.

    *@incubating*
    """
    createdBy: DigitalIdentity
    """
    *@incubating*
    """
    deployStatus: DeployStatus
    """
    *@incubating*
    """
    enqueuedAt: DateTime
    """
    Not globally unique low-level DB identifier.

    *@stable*
    """
    id: ID!
    """
    When allowedToModifyFor has values then the value for this field is true for all users which are not mentioned within values of allowedToModifyFor

    *@incubating*
    """
    isReadOnly: Boolean
    """
    *@incubating*
    """
    latestDeploymentStartedAt: DateTime
    """
    Timestamp indicating when the instance was last updated.

    *@incubating*
    """
    modifiedAt: DateTime
    """
    DigitalIdentity of the user who last updated the instance.

    *@incubating*
    """
    modifiedBy: DigitalIdentity
    """
    *@incubating*
    """
    name: String!
    """
    *@incubating*
    """
    package: File!
    """
    Primary key.

    Represents a specific *candidate key* used as a default for relationships
    and lookups.

    *@stable*
    """
    pk(typeName: String): PK!
    """
    Primary keys for all types the instance relates to.

    *@incubating*
    """
    pks: [PK!]
    """
    The field is managed internally, links are set automatically when some other model references this model. The main goal of the field to remove automatically instances on removing target models referenced by instance of ModelsOrderingInfo

    *@incubating*
    """
    referencesFromModelsOrderingInfo: [ModelsOrderingInfo!]
    """
    GraphQL type name.

    *@incubating*
    """
    typeName: String!
    """
    Globally unique identifier.

    *@stable*
    """
    uid: UUID!
}

"""
*@incubating*
"""
type Function implements Auditable & Model & Node {
    """
    When values are present then modifying/deleting is allowed only by users mentioned in this list. When a model is mutated and empty list is added that it is treated as a setting of 'allowedToModifyFor' for the current user otherwise pass null to 'allowedToModifyFor' to turn off read only mode for all other users

    *@incubating*
    """
    allowedToModifyFor: [UUID!]
    """
    Audit log of changes.

    *@incubating*
    """
    auAudit: Audit
    """
    Timestamp indicating when the instance was created.

    *@incubating*
    """
    createdAt: DateTime
    """
    DigitalIdentity of the user who created the instance.

    *@incubating*
    """
    createdBy: DigitalIdentity
    """
    *@incubating*
    """
    deployStatus: DeployStatus
    """
    *@incubating*
    """
    enqueuedAt: DateTime
    """
    *@incubating*
    """
    fun: File!
    """
    Not globally unique low-level DB identifier.

    *@stable*
    """
    id: ID!
    """
    When allowedToModifyFor has values then the value for this field is true for all users which are not mentioned within values of allowedToModifyFor

    *@incubating*
    """
    isReadOnly: Boolean
    """
    *@incubating*
    """
    latestCreatedRevision: String
    """
    *@incubating*
    """
    latestDeploymentStartedAt: DateTime
    """
    Timestamp indicating when the instance was last updated.

    *@incubating*
    """
    modifiedAt: DateTime
    """
    DigitalIdentity of the user who last updated the instance.

    *@incubating*
    """
    modifiedBy: DigitalIdentity
    """
    *@incubating*
    """
    name: String!
    """
    Primary key.

    Represents a specific *candidate key* used as a default for relationships
    and lookups.

    *@stable*
    """
    pk(typeName: String): PK!
    """
    Primary keys for all types the instance relates to.

    *@incubating*
    """
    pks: [PK!]
    """
    *@incubating*
    """
    ready: String
    """
    *@incubating*
    """
    readyRevision: String
    """
    The field is managed internally, links are set automatically when some other model references this model. The main goal of the field to remove automatically instances on removing target models referenced by instance of ModelsOrderingInfo

    *@incubating*
    """
    referencesFromModelsOrderingInfo: [ModelsOrderingInfo!]
    """
    *@incubating*
    """
    runtime: String
    """
    *@incubating*
    """
    specialization: FunctionSpecialization
    """
    *@incubating*
    """
    tag: String!
    """
    GraphQL type name.

    *@incubating*
    """
    typeName: String!
    """
    Globally unique identifier.

    *@stable*
    """
    uid: UUID!
    """
    *@incubating*
    """
    url: Url!
    """
    *@incubating*
    """
    urn: Urn
    """
    *@incubating*
    """
    version: String
}

########   Non-persistent types    ########
type FunctionRuntimeResponse {
    url: Url!
}

########   Inputs    ########
input CreateFunctionInput {
    fun: Upload!
}

input UpsertFunctionInput {
    uid: UUID
    fun: Upload!
}

enum FunctionLanguage {
    Typescript
    Node
}

input FunctionRuntimeInput {
    language: FunctionLanguage!
}

type Integration {
    name: String
    phase: String
}

input CreateIntegrationInput {
    package: Upload!
}

input UpsertIntegrationInput {
    uid: UUID
    package: Upload!
}

type FunctionConnection {
    edges: [FunctionConnectionFunctionEdge!]
    pageInfo: PageInfo!
    totalCount: Int!
}

type FunctionConnectionFunctionEdge {
    cursor: String!
    node: Function
}

input FunctionInput {
    allowedToModifyFor: [UUID!]
    createdAt: DateTime
    createdBy: DigitalIdentityInput
    deployStatus: DeployStatus
    enqueuedAt: DateTime
    fun: Upload
    latestCreatedRevision: String
    latestDeploymentStartedAt: DateTime
    modifiedAt: DateTime
    modifiedBy: DigitalIdentityInput
    name: String
    pk: PKRef
    ready: String
    readyRevision: String
    runtime: String
    specialization: FunctionSpecialization
    tag: String
    uid: UUID
    url: Url
    urn: Urn
    version: String
}

input DigitalIdentityInput {
    _viaxKeycloakDigitalIdentity: ViaxKeycloakDigitalIdentityInput
    allowedToModifyFor: [UUID!]
    createdAt: DateTime
    createdBy: DigitalIdentityInput
    diLogin: String
    modifiedAt: DateTime
    modifiedBy: DigitalIdentityInput
    pk: PKRef
    typeName: String
    uid: UUID
}

input ViaxKeycloakDigitalIdentityInput {
    allowedToModifyFor: [UUID!]
    createdAt: DateTime
    createdBy: DigitalIdentityInput
    diLogin: String
    modifiedAt: DateTime
    modifiedBy: DigitalIdentityInput
    pk: PKRef
    uid: UUID
}

"""
Input to refer existing model

*@incubating*
"""
input PKRef {
    """
    type name can be skipped if model reference is passed for a field which value type is object specific

    *@incubating*
    """
    typeName: String
    """
    Primary key value which relates to type identified by `typeName`

    *@incubating*
    """
    value: ID!
}

########   Queries/Mutations    ########
type Query {
    runtimeTemplate(input: FunctionRuntimeInput): FunctionRuntimeResponse
        @resolvedBy(resolvers: ["runtimeTemplate"])
    getIntegrations: [Integration]
        @resolvedBy(resolvers: ["getKamelIntegrations"])

    """
    *@incubating*
    """
    getIntegrationDeployment(
        id: ID
        name: String
        pk: PKRef
        uid: UUID
    ): IntegrationDeployment

    getFunction(id: ID, name: String, pk: PKRef, uid: UUID): Function

    filterFunction(
        _after: String
        _before: String
        _filter: String
        _first: Int
        _last: Int
        _orderBy: [FunctionOrderByInput!]
        id: [ID!]
        name: [String!]
        pk: [PKRef!]
        uid: [UUID!]
    ): FunctionConnection
}

type Mutation {
    createFunction(input: CreateFunctionInput!): Function
        @override
        @resolvedBy(
            resolvers: ["functionPreprocess", "createModelMutationResolver"]
        )
    upsertFunction(input: UpsertFunctionInput!): Function
        @override
        @resolvedBy(
            resolvers: ["functionPreprocess", "upsertModelMutationResolver"]
        )
    deleteFunction(uid: UUID!, _force: Boolean @deprecated): Function
        @override
        @resolvedBy(resolvers: ["deleteFunction"])
    deployFunction(uid: UUID!): Function
        @resolvedBy(resolvers: ["deployFunctionResolver"])

    createIntegrationDeployment(
        input: CreateIntegrationInput!
    ): IntegrationDeployment
        @override
        @resolvedBy(
            resolvers: ["integrationPreprocess", "createModelMutationResolver"]
        )
    upsertIntegrationDeployment(
        input: UpsertIntegrationInput!
    ): IntegrationDeployment
        @override
        @resolvedBy(
            resolvers: ["integrationPreprocess", "upsertModelMutationResolver"]
        )
    deleteIntegrationDeployment(
        uid: UUID!
        _force: Boolean @deprecated
    ): IntegrationDeployment
        @override
        @resolvedBy(resolvers: ["deleteIntegration"])
    deployIntegrationDeployment(uid: UUID!): IntegrationDeployment
        @resolvedBy(resolvers: ["deployIntegrationResolver"])
}
